### PR TITLE
Fix for Roller shutter

### LINKED ISSUE #173: Rollershutter3 not recognised as gate anymore
Since latest update the rollershutter3 isn't recognised as gate anymore, so will not show up in CarPlay.
In version 1.4.0 it works, but not in 1.4.1 and the latest beta

### PR DESCRIPTION
**Pull request by mkz212**
@ilcato this should fix #173

### CODE REVIEW

File: src/fibaroAccessory.ts [hunk 1]
```diff
@@ -200,23 +207,17 @@ export class FibaroAccessory {
...
-          controlType === 56 || controlType === 57) {
-          // it's a garage door
-          service = this.platform.Service.GarageDoorOpener;
-          this.mainCharacteristics =
-              [this.platform.Characteristic.CurrentDoorState,
-                this.platform.Characteristic.TargetDoorState,
-                this.platform.Characteristic.ObstructionDetected];
-          break;
-        }
+      case 'com.fibaro.baseShutter':
```
Comment (ilcato) [inline src/fibaroAccessory.ts:214]: @mkz212, Doesn't compile. Compile the code before submitting a PR.
